package com.example.marvel.model.charactersDetails

data class ResultsItem(val creators: Creators,
                       val issueNumber: Int = 0,
                       val isbn: String = "",
                       val description: String = "",
                       val title: String = "",
                       val diamondCode: String = "",
                       val characters: Characters,
                       val urls: List<UrlsItem>?,
                       val ean: String = "",
                       val modified: String = "",
                       val id: Int = 0,
                       val prices: List<PricesItem>?,
                       val events: Events,
                       val pageCount: Int = 0,
                       val thumbnail: Thumbnail,
                       val images: List<ImagesItem>?,
                       val stories: Stories,
                       val digitalId: Int = 0,
                       val format: String = "",
                       val upc: String = "",
                       val dates: List<DatesItem>?,
                       val resourceURI: String = "",
                       val variantDescription: String = "",
                       val issn: String = "",
                       val series: Series)